import Foundation

extension LocationTarget {
    /// MapKit place names and user-renamed favourites stay intact. Only names
    /// generated by Roam Control are translated, without modifying saved data.
    func displayName(locale: Locale) -> String {
        let generated = (name == "Dropped Pin" && ["Selected from the map", "Finding nearby address…"].contains(subtitle))
            || (name == "Entered Location" && ["Entered using coordinates", "Finding nearby address…"].contains(subtitle))
            || (name == "Route Start" && subtitle.hasPrefix("Starting point for "))
            || (name.hasPrefix("Walking to ") && subtitle.hasSuffix("% complete"))
        return generated ? AppLocalization.text(name, locale: locale) : name
    }

    func displaySubtitle(locale: Locale) -> String {
        switch subtitle {
        case "Selected from the map", "Entered using coordinates", "Finding nearby address…":
            return AppLocalization.text(subtitle, locale: locale)
        default:
            if (name == "Route Start" && subtitle.hasPrefix("Starting point for "))
                || (name.hasPrefix("Walking to ") && subtitle.hasSuffix("% complete")) {
                return AppLocalization.text(subtitle, locale: locale)
            }
            return subtitle
        }
    }
}
